import path from "node:path";
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import { tanstackRouter } from "@tanstack/router-plugin/vite";

// @ts-expect-error process is a nodejs global
const host = process.env.TAURI_DEV_HOST;

// https://vite.dev/config/
export default defineConfig(async ({ mode }) => {
  const localOwnerBuild = mode === "local-owner";

  return {
    plugins: [
      tanstackRouter({
        target: "react",
        routesDirectory: "./src/app/routes",
        generatedRouteTree: localOwnerBuild
          ? "./src/app/routeTree.local-owner.gen.ts"
          : "./src/app/routeTree.gen.ts",
        virtualRouteConfig: localOwnerBuild
          ? "./src/app/routes.local-owner.ts"
          : "./src/app/routes.ts",
        quoteStyle: "double",
        semicolons: true,
        routeTreeFileHeader: [
          "// biome-ignore-all lint: generated by TanStack Router",
        ],
      }),
      react(),
    ],
    resolve: {
      alias: [
        ...(localOwnerBuild
          ? [
              {
                find: /^@\/app\/router$/,
                replacement: path.resolve(
                  __dirname,
                  "./src/app/router.local-owner.tsx",
                ),
              },
              {
                find: /^@\/features\/onboarding\/ui\/MachineOnboardingFlow$/,
                replacement: path.resolve(
                  __dirname,
                  "./src/features/onboarding/ui/MachineOnboardingFlow.local-owner.tsx",
                ),
              },
            ]
          : []),
        { find: "@", replacement: "/src" },
        {
          find: "@features-manifest",
          replacement: path.resolve(__dirname, "../preview-features.json"),
        },
      ],
    },

    // Vite options tailored for Tauri development and only applied in `tauri dev` or `tauri build`
    //
    // 1. prevent Vite from obscuring rust errors
    clearScreen: false,
    // 2. tauri expects a fixed port, fail if that port is not available
    server: {
      port: parseInt(process.env.VITE_PORT || "1420", 10),
      strictPort: true,
      host: host || false,
      hmr: host
        ? {
            protocol: "ws",
            host,
            port: parseInt(process.env.VITE_HMR_PORT || "1421", 10),
          }
        : undefined,
      watch: {
        // 3. tell Vite to ignore watching `src-tauri`
        ignored: ["**/src-tauri/**"],
      },
    },
  };
});
